api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    path('v1/list/grantgoal/', views.ListGrantGoalAPIView.as_view(), name ="list_gg_api"),
    path('v1/detail/grantgoal/<int:pk>', views.DetailGrantGoalAPIView.as_view(), name ="detail_gg_api"),
    path('v1/create/grantgoal/', views.CreateGrantGoalAPIView.as_view(), name ="create_gg_api"),
    path('v1/update/grantgoal/<int:pk>', views.UpdateGrantGoalAPIView.as_view(), name ="update_gg_api"),
    path('v1/delete/grantgoal/<int:pk>', views.DeleteGrantGoalAPIView.as_view(), name ="delete_gg_api"),
    
    
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"


urlpatterns = [
    ##### GRANTGOAL URLS #####
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="list_gg"),
    path('new/grantgoal/', views.NewGrantGoal.as_view(), name="create_gg"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_gg"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_gg"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_gg"),

    ##### SUBGRANTGOAL URLS #####
    path('list/subgrantgoal/', views.ListSubGrantGoal.as_view(), name="list_sgg"),
    path('new/subgrantgoal/', views.NewSubGrantGoal.as_view(), name="create_sgg"),
    path('detail/subgrantgoal/<int:pk>/', views.DetailSubGrantGoal.as_view(), name="detail_sgg"),
    path('update/subgrantgoal/<int:pk>/', views.UpdateSubGrantGoal.as_view(), name="update_sgg"),
    path('delete/subgrantgoal/<int:pk>/', views.DeleteSubGrantGoal.as_view(), name="delete_sgg"),


    ### Issues ####
    path('list/issue/', views.ListIssue.as_view(), name="list_issue"),
    path('new/issue/', views.NewIssue.as_view(), name="create_issue"),
    path('detail/issue/<int:pk>/', views.DetailIssue.as_view(), name="detail_issue"),
    path('update/issue/<int:pk>/', views.UpdateIssue.as_view(), name="update_issue"),
    path('delete/issue/<int:pk>/', views.DeleteIssue.as_view(), name="delete_issue"),


    ### AREA ####
    path('new/area/', views.NewArea.as_view(), name="create_area"),
    path('list/area/', views.ListArea.as_view(), name="list_area"),
    path('detail/area/<int:pk>/', views.DetailArea.as_view(), name="detail_area"),
    path('update/area/<int:pk>/', views.UpdateArea.as_view(), name="update_area"),
    path('delete/area/<int:pk>/', views.DeleteArea.as_view(), name="delete_area"),


    ### GOAL ###
    path('goal/new/', views.NewGoal.as_view(), name='create_goal'),
    path('goal/', views.ListGoal.as_view(), name='list_goal'),
    path('goal/<int:pk>/', views.DetailGoal.as_view(), name='detail_goal'),
    path('goal/update/<int:pk>/', views.UpdateGoal.as_view(), name='update_goal'),
    path('goal/delete/<int:pk>/', views.DeleteGoal.as_view(), name='delete_goal'),

]

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
    path('api/', include("api.urls")),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta
from django.urls import reverse

# Create your models here.



CHOICES_LEVEL = (
    ("HEIGHT", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW"),
)

CHIOCES_STATE = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class GrantGoal(models.Model):
    ggname = models.CharField(max_length=64, default="Generic Grant Goal")
    description = models.CharField(max_length=128, default="Generic Grant Goal description")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True) 
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL)
    state = models.CharField(max_length=16, choices=CHIOCES_STATE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.ggname
    
    def get_absolute_url(self):
        return reverse("detail_gg", kwargs={"pk": self.pk})
    
@receiver(post_save, sender=GrantGoal)
def auto_final_date_GG(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()




class Area(models.Model):
    area_name = models.CharField(max_length=32, default="Generic Area")
    description = models.CharField(max_length=128, default="Generic Activities")

    def __str__(self):
        return self.area_name




CHOICES_LEVEL_SUB = (
    ("HEIGHT", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW"),
)

CHIOCES_STATE_SUB = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class SubGrantGoal(models.Model):
    sggname = models.CharField(max_length=64, default="Generic Sub Grant Goal")
    description = models.CharField(max_length=128, default="Generic Sub Grant Goal description")
    grantgoal = models.ForeignKey(GrantGoal, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL_SUB)
    state = models.CharField(max_length=16, choices=CHIOCES_STATE_SUB)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.sggname


@receiver(post_save, sender=SubGrantGoal)
def auto_final_date_SGG(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()






CHOICES_LEVEL_GOAL = (
    ("HEIGHT", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW"),
)

CHIOCES_STATE_GOAL = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class Goal(models.Model):
    goalname = models.CharField(max_length=64, default="Generic Goal")
    description = models.CharField(max_length=128, default="Generic Goal description")
    subgrantgoal = models.ForeignKey(SubGrantGoal, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL_GOAL)
    state = models.CharField(max_length=16, choices=CHIOCES_STATE_GOAL)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.goalname


@receiver(post_save, sender=Goal)
def auto_final_date_G(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()





CHOICES_LEVEL_ISSUE = (
    ("HEIGHT", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW"),
)

CHIOCES_STATE_ISSUE = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class Issue(models.Model):
    issuename = models.CharField(max_length=64, default="Generic Issue")
    description = models.CharField(max_length=128, default="Generic Issue description")
    goal = models.ForeignKey(Goal, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL_ISSUE)
    state = models.CharField(max_length=16, choices=CHIOCES_STATE_ISSUE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.issuename



@receiver(post_save, sender=Issue)
def auto_final_date_I(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()

core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from core import models
from core import forms 

# Create your views here.

# # # #  C R U D G R A N T G O A L  # # # # #

### CREATE
class NewGrantGoal(generic.CreateView):
    template_name = "core/create_gg.html"
    model = models.GrantGoal
    form_class = forms.NewGrantGoalForm
    success_url = reverse_lazy("core:list_gg")

## List
class ListGrantGoal(generic.View):
    template_name = "core/list_gg.html"
    context = {}

    def get(self, request):
        self.context = {
            "grantgoals": models.GrantGoal.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)
    
## Detail
class DetailGrantGoal(generic.View):
    template_name = "core/detail_gg.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "grantgoal": models.GrantGoal.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)

### UPDATE
class UpdateGrantGoal(generic.UpdateView):
    template_name = "core/update_gg.html"
    model = models.GrantGoal
    form_class = forms.UpdateGrantGoalForm
    success_url = reverse_lazy("core:list_gg")


### DELETE
class DeleteGrantGoal(generic.DeleteView):
    template_name = "core/delete_gg.html"
    model = models.GrantGoal
    success_url = reverse_lazy("core:list_gg")



# # # #  C R U D   S U B G R A N T G O A L  # # # # #

### CREATE
class NewSubGrantGoal(generic.CreateView):
    template_name = "core/create_sgg.html"
    model = models.SubGrantGoal
    form_class = forms.NewSubGrantGoalForm
    success_url = reverse_lazy("core:list_sgg")

### RETRIEVE
## List
class ListSubGrantGoal(generic.ListView):
    template_name = "core/list_sgg.html"
    queryset = models.SubGrantGoal.objects.filter(status=True)

## Detail
class DetailSubGrantGoal(generic.DetailView):
    template_name = "core/detail_sgg.html"
    model = models.SubGrantGoal


### UPDATE
class UpdateSubGrantGoal(generic.UpdateView):
    template_name = "core/update_sgg.html"
    model = models.SubGrantGoal
    form_class = forms.UpdateSubGrantGoalForm
    success_url = reverse_lazy("core:list_sgg")


### DELETE
class DeleteSubGrantGoal(generic.DeleteView):
    template_name = "core/delete_sgg.html"
    model = models.SubGrantGoal
    success_url = reverse_lazy("core:list_sgg")



# # # #  C R U D G O A L  # # # # #

### CREATE
class NewGoal(generic.CreateView):
    template_name = "core/create_goal.html"
    model = models.Goal
    form_class = forms.NewGoalForm
    success_url = reverse_lazy("core:list_goal")

## List
class ListGoal(generic.View):
    template_name = "core/list_goal.html"
    context = {}

    def get(self, request):
        self.context = {
            "goals": models.Goal.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)
    
## Detail
class DetailGoal(generic.View):
    template_name = "core/detail_goal.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "goal": models.Goal.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)

### UPDATE
class UpdateGoal(generic.UpdateView):
    template_name = "core/update_goal.html"
    model = models.Goal
    form_class = forms.UpdateGoalForm
    success_url = reverse_lazy("core:list_goal")


### DELETE
class DeleteGoal(generic.DeleteView):
    template_name = "core/delete_goal.html"
    model = models.Goal
    success_url = reverse_lazy("core:list_goal")



# # # #  C R U D   ISSUES  # # # # #

### CREATE
class NewIssue(generic.CreateView):
    template_name = "core/create_issue.html"
    model = models.Issue
    form_class = forms.NewIssueForm
    success_url = reverse_lazy("core:list_issue")


## List

class ListIssue(generic.View):
    template_name = "core/list_issue.html"
    context = {}

    def get(self, request):
        self.context = {
            "issues": models.Issue.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)
    

## Detail
class DetailIssue(generic.View):
    template_name = "core/detail_issue.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "issue": models.Issue.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)


### UPDATE
class UpdateIssue(generic.UpdateView):
    template_name = "core/update_issue.html"
    model = models.Issue
    form_class = forms.UpdateIssueForm
    success_url = reverse_lazy("core:list_issue")


### DELETE
class DeleteIssue(generic.DeleteView):
    template_name = "core/delete_issue.html"
    model = models.Issue
    success_url = reverse_lazy("core:list_issue")








# # # #  C R U D   AREA  # # # # #

# CREATE
class NewArea(generic.CreateView):
    template_name = "core/create_area.html"
    model = models.Area
    form_class = forms.NewAreaForm
    success_url = reverse_lazy("core:list_area")

# LIST
class ListArea(generic.View):
    template_name = "core/list_area.html"
    context = {}

    def get(self, request):
        self.context = {
            "areas": models.Area.objects.all()
        }
        return render(request, self.template_name, self.context)

# DETAIL
class DetailArea(generic.View):
    template_name = "core/detail_area.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "area": models.Area.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)

# UPDATE
class UpdateArea(generic.UpdateView):
    template_name = "core/update_area.html"
    model = models.Area
    form_class = forms.UpdateAreaForm
    success_url = reverse_lazy("core:list_area")

# DELETE
class DeleteArea(generic.DeleteView):
    template_name = "core/delete_area.html"
    model = models.Area
    success_url = reverse_lazy("core:list_area")

templates/core/create_gg.html
{% extends "base/base.html" %}

{% block title %}NEW GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-outline-success form-control">New Grant Goal</button>
            <br>
            <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/create_issue.html
{% extends "base/base.html" %}

{% block title %}NEW ISSUE VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-outline-success form-control">Create Issue</button>
            <br>
            <a href="{% url 'core:list_issue' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete_gg.html
{% extends "base/base.html" %}

{% block title %}DELETE GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h3>¿Realmente deseas eliminar el GrantGoal: "{{ object }}"?</h3>
            
            <button type="submit" class="btn btn-outline-danger">Delete GrantGoal</button>
            <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete_goal.html
{% extends "base/base.html" %}

{% block title %}DELETE GOAL VIEW{% endblock title %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <h3>¿Realmente deseas eliminar el Goal: "{{ object }}"?</h3>
    <button type="submit" class="btn btn-outline-danger">Delete Goal</button>
    <a href="{% url 'core:list_goal' %}" class="btn btn-outline-warning">Cancel</a>
</form>
{% endblock content %}

templates/core/delete_issue.html
{% extends "base/base.html" %}

{% block title %}DELETE ISSUE VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h3>Are you sure you want to delete the Issue: "{{ object }}"?</h3>
            
            <button type="submit" class="btn btn-outline-danger">Delete Issue</button>
            <a href="{% url 'core:list_issue' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete_sgg.html
{% extends "base/base.html" %}

{% block title %}DELETE SUBGRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h3>¿Realmente deseas eliminar el SubGrantGoal: "{{ object }}"?</h3>
            
            <button type="submit" class="btn btn-outline-danger">Delete SubGrantGoal</button>
            <a href="{% url 'core:list_sgg' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/detail_area.html
{% extends "base/base.html" %}

{% block title %}DETAIL AREA VIEW{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          General Data
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          This is the area name: <strong>{{ area.area_name }}</strong> It is the description: {{ area.description }}
        </div>
      </div>
    </div>
  </div>
  <a href="{% url 'core:list_area' %}" class="btn btn-outline-secondary mt-3">Return</a>
{% endblock content %}

templates/core/detail_goal.html
{% extends "base/base.html" %}

{% block title %}DETAIL GOAL VIEW{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                General Data
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                This is the goal name: <strong>{{ goal.goalname }}</strong>. It is the description: {{ goal.description }}, and its progress is: <code>{{ goal.progress }} %</code>.
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Date Data
            </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                This is the goal timestamp: <strong>{{ goal.timestamp }}</strong>. It is the days duration to the goal: {{ goal.days_duration }}, and its final date is: <code>{{ goal.final_date }}</code>.
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Status Data
            </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                This is the goal state: <strong>{{ goal.state }}</strong>, the goal status: {{ goal.status }}, and the goal priority: <code>{{ goal.priority }}</code>.
            </div>
        </div>
    </div>
</div>
<a href="{% url 'core:list_goal' %}" class="btn btn-outline-secondary mt-3">Return</a>
{% endblock content %}

templates/core/detail_sgg.html
{% extends "base/base.html" %}

{% block title %}DETAIL SUBGRANT GOAL VIEW{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          General Data
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          This is the grantgoal name: <strong>{{ object.sggname }}</strong> It is the description: {{ object.description }}, and its progress is: <code>{{ object.progress }} %</code>
          Related grantgoal: <code>{{ object.grantgoal }} </code>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          This is the grantgoal timestamp.<strong>{{ object.timestamp }}</strong> It is the days duration to the grantgoal: {{ object.days_duration }}, and its final data is: <code>{{ object.final_date }}</code>.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Data
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          This is the grantgoal state: <strong>{{ object.state }}</strong> and  It is the grantgoal status: {{ object.status }} and it is the grantgoal priority:  <code>{{ object.priority }}</code>.
        </div>
      </div>
    </div>
  </div>
  <a href="{% url 'core:list_sgg' %}" class="btn btn-outline-secondary mt-3">Return</a>
{% endblock content %}

templates/core/list_goal.html
{% extends "base/base.html" %}

{% block title %}LIST GOAL VIEW{% endblock title %}

{% block content %}
    <center><h3>Goal List</h3></center>
    <br>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>DESCRIPTION</th>
            <th>TIMESTAMP</th>
            <th>SUBGRANTGOAL</th>
            <th>AREA</th>
            <th>USER</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for goal in goals %}
                <tr>
                    <td>{{ goal.id }}</td>
                    <td>{{ goal.goalname }}</td>
                    <td>{{ goal.description }}</td>
                    <td>{{ goal.timestamp }}</td>
                    <td>{{ goal.subgrantgoal }}</td>
                    <td>{{ goal.area }}</td>
                    <td>{{ goal.user }}</td>
                    <td><a href="{% url 'core:detail_goal' goal.pk %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'core:update_goal' goal.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_goal' goal.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <hr>
    <a href="{% url 'core:create_goal' %}" class="btn btn-outline-success form-control">New Goal</a>
{% endblock content %}

templates/core/list_issue.html
{% extends "base/base.html" %}

{% block title %}LIST ISSUE VIEW{% endblock title %}

{% block content %}
    <center><h3>Issue List</h3></center>
    <br>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>ISSUE</th>
            <th>USER</th>
            <th>GOAL</th>
            <th>AREA</th>
            <th>TIMESTAMP</th>
            <th>PRIORITY</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for issue in issues %}
                <tr>
                    <td>{{ issue.id }}</td>
                    <td>{{ issue.issuename }}</td>
                    <td>{{ issue.user }}</td>
                    <td>{{ issue.grantgoal }}</td>
                    <td>{{ issue.area }}</td>
                    <td>{{ issue.timestamp }}</td>
                    <td> {{ issue.priority }}</td>
                    <td><a href="{% url 'core:detail_issue' issue.pk %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'core:update_issue' issue.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_issue' issue.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <hr>
    <a href="{% url 'core:create_issue' %}" class="btn btn-outline-success form-control">New Issue</a>
{% endblock content %}

templates/core/update_goal.html
{% extends "base/base.html" %}

{% block title %}UPDATE GOAL VIEW{% endblock title %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <button style="margin: 2%;" type="submit" class="btn btn-outline-primary form-control">Update Goal</button>
    <br>
    <a href="{% url 'core:list_goal' %}" class="btn btn-outline-warning form-control">Cancel</a>
</form>
{% endblock content %}

templates/core/update_issue.html
{% extends "base/base.html" %}

{% block title %}UPDATE ISSUE VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-outline-primary form-control">Update Issue</button>
            <br>
            <a href="{% url 'core:list_issue' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/update_sgg.html
{% extends "base/base.html" %}

{% block title %}UPDATE SUBGRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-outline-primary form-control">Update Sub Grant Goal</button>
            <br>
            <a href="{% url 'core:list_sgg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}